Repository mahirr476/pg_admin, pull requests merged in 2025-02, with the labels that each got.

#4 Initial System and Plan Design Implementation
  docs/design/img/Security_Architecture.png
  docs/design/img/admin_interactions.png
  docs/design/img/autt_flow.png
  docs/design/img/core_compo.png
  docs/design/img/db.png
  docs/design/img/level_0_dfd.png
  docs/design/img/module_system_interactions.png
  docs/design/img/system_de.png
  docs/design/img/use_case_dia.png
  docs/design/img/website_management_flows.png
  docs/design/system-design-template.md
  docs/plan/project-plan-template.md
Labels: documentation

#19 18-update-design-pg-parasole
  pg_admin/client/src/app/about-us/page.tsx
  pg_admin/client/src/app/admin/paragon/about/page.tsx
  pg_admin/client/src/app/admin/paragon/home/page.tsx
  pg_admin/client/src/app/admin/paragon/milestones/page.tsx
  pg_admin/client/src/app/career/page.tsx
  pg_admin/client/src/app/contact/page.tsx
  pg_admin/client/src/app/dashboard/page.tsx
  pg_admin/client/src/app/home/page.tsx
  pg_admin/client/src/app/media/page.tsx
  pg_admin/client/src/app/milestones/page.tsx
  pg_admin/client/src/components/layout/Header.tsx
  pg_admin/client/src/components/paragon/about/aboutUs1.tsx
  pg_admin/client/src/components/paragon/about/aboutUs2.tsx
  pg_admin/client/src/components/paragon/about/aboutUs3.tsx
  pg_admin/client/src/components/paragon/about/aboutUs4.tsx
  pg_admin/client/src/components/paragon/about/aboutUs5.tsx
  pg_admin/client/src/components/paragon/about/aboutUs6.tsx
  pg_admin/client/src/components/paragon/about/csr1.tsx
  pg_admin/client/src/components/paragon/about/csr2.tsx
  pg_admin/client/src/components/paragon/about/csr3.tsx
  pg_admin/client/src/components/paragon/about/csr4.tsx
  pg_admin/client/src/components/paragon/about/csr5.tsx
  pg_admin/client/src/components/paragon/about/csr6.tsx
  pg_admin/client/src/components/paragon/home/firstSection.tsx
  pg_admin/client/src/components/paragon/home/fiveSection.tsx
  pg_admin/client/src/components/paragon/home/fourSection.tsx
  pg_admin/client/src/components/paragon/home/secondSection.tsx
  pg_admin/client/src/components/paragon/home/sixSection.tsx
  pg_admin/client/src/components/paragon/home/thirdSection.tsx
  pg_admin/client/src/components/paragon/milestones/milestones-hero.tsx
  pg_admin/client/src/components/paragon/milestones/milestones-main.tsx
  pg_admin/client/src/components/ui/table.tsx
Labels: UI/UX

#23 21/design tweaks
  pg_admin/client/package-lock.json
  pg_admin/client/package.json
  pg_admin/client/src/app/admin/parasole/about/page.tsx
  pg_admin/client/src/app/admin/parasole/compliance/page.tsx
  pg_admin/client/src/app/admin/parasole/home/page.tsx
  pg_admin/client/src/app/layout.tsx
  pg_admin/client/src/components/layout/Header.tsx
  pg_admin/client/src/components/layout/MainContent.tsx
  pg_admin/client/src/components/layout/MainLayout.tsx
  pg_admin/client/src/components/layout/Navigation.tsx
  pg_admin/client/src/components/layout/Sidebar.tsx
  pg_admin/client/src/components/ui/badge.tsx
  pg_admin/client/src/context/SidebarContext.tsx
  pg_admin/client/src/providers/SidebarContext.tsx
  pg_admin/client/src/providers/WebsiteProvider.tsx
  pg_admin/client/src/providers/auth-provider.tsx
Labels: UI/UX, front-end

#24 18-update-design-pg-parasole
  pg_admin/client/package-lock.json
  pg_admin/client/package.json
  pg_admin/client/src/app/admin/paragon/buisness/page.tsx
  pg_admin/client/src/app/admin/paragon/business/page.tsx
  pg_admin/client/src/app/admin/paragon/career/page.tsx
  pg_admin/client/src/app/admin/paragon/companies/page.tsx
  pg_admin/client/src/app/admin/paragon/media/page.tsx
  pg_admin/client/src/components/paragon/buisness/buisness1.tsx
  pg_admin/client/src/components/paragon/buisness/buisness2.tsx
  pg_admin/client/src/components/paragon/career/careerArea.tsx
  pg_admin/client/src/components/paragon/career/careerHero.tsx
  pg_admin/client/src/components/paragon/companies/page.tsx
  pg_admin/client/src/components/paragon/media/mediaHero.tsx
  pg_admin/client/src/components/paragon/media/mediaMain.tsx
  pg_admin/client/src/components/ui/label.tsx
Labels: UI/UX
